// Command idlgen generates a typed Go helper file from the Milon IDL index.
//
// Like Rust derive macros, the generated code is auto-managed: it lives in
// the SDK gen package and is regenerated with:
//
//	go run ./tools/idlgen -index provider/IDL/index.json
//
// The output gen/idl_gen.go contains:
//
//  1. DefaultIDLs - all IDL definitions as inline constants, mirroring the
//     JS SDK's DEFAULT_IDLS (as const).
//
//  2. Typed instruction builders (gen.Token.ClaimFaucet.Args(...).Encode())
//     that are rebound to the loaded IDLs on every milon.NewClient call.
//     Instruction arguments use generated types (e.g. TokenMetadata) and are
//     converted to the provider wire format automatically on Encode.
//
//  3. Generated structs for every custom IDL type (e.g. TokenMetadata) and
//     DecodeView methods for view instructions, so a view response body can
//     be decoded directly:
//
//     supply, err := gen.Token.TotalSupply.DecodeView(viewResult.HTTPResponseBody)
//     meta, err := gen.Token.Metadata.DecodeView(viewResult.HTTPResponseBody)
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/milon-labs/milon-go-sdk/provider"
)

var (
	indexPath = flag.String("index", "provider/IDL/index.json", "path to IDL index.json")
	outPath   = flag.String("out", "gen/idl_gen.go", "output Go file path")
	pkgName   = flag.String("pkg", "gen", "generated package name")
)

type indexConfig struct {
	Apps []struct {
		AppID uint8  `json:"app_id"`
		IDL   string `json:"idl"`
		Name  string `json:"name"`
	} `json:"apps"`
}

type appInfo struct {
	name string
	idl  provider.IDL
}

type importSet struct {
	crypto bool
	big    bool
}

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "idlgen:", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := os.ReadFile(*indexPath)
	if err != nil {
		return fmt.Errorf("read index: %w", err)
	}
	var index indexConfig
	if err := json.Unmarshal(data, &index); err != nil {
		return fmt.Errorf("parse index: %w", err)
	}

	dir := filepath.Dir(*indexPath)
	var apps []appInfo
	for _, app := range index.Apps {
		idlData, err := os.ReadFile(filepath.Join(dir, app.IDL))
		if err != nil {
			return fmt.Errorf("read IDL %s: %w", app.IDL, err)
		}
		var idl provider.IDL
		if err := json.Unmarshal(idlData, &idl); err != nil {
			return fmt.Errorf("parse IDL %s: %w", app.IDL, err)
		}
		apps = append(apps, appInfo{name: app.Name, idl: idl})
	}

	src, err := generate(apps, *pkgName)
	if err != nil {
		return err
	}
	if err := os.WriteFile(*outPath, []byte(src), 0644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	fmt.Printf("idlgen: wrote %s (%d apps)\n", *outPath, len(apps))
	return nil
}

func generate(apps []appInfo, pkg string) (string, error) {
	var imp importSet
	for _, app := range apps {
		types := buildTypeMap(app)
		for _, ix := range app.idl.Instructions {
			for _, arg := range ix.Args {
				goReturnType(arg.Type, &imp, app.name, types)
			}
			if ix.Kind == "view" && ix.Returns.Type != "" {
				goReturnType(ix.Returns.Type, &imp, app.name, types)
			}
		}
		for _, t := range app.idl.Types {
			if t.Kind == "struct" {
				for _, f := range t.Fields {
					goReturnType(f.Type, &imp, app.name, types)
				}
			}
		}
	}
	// Conversion helpers are always emitted, so their imports are always used.
	imp.crypto = true
	imp.big = true

	var b strings.Builder
	b.WriteString("// Code generated by milon idlgen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s (regenerate with: go run ./tools/idlgen)\n\n", *indexPath)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if imp.big {
		b.WriteString("\t\"math/big\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/milon-labs/milon-go-sdk/api\"\n")
	if imp.crypto {
		b.WriteString("\t\"github.com/milon-labs/milon-go-sdk/crypto\"\n")
	}
	if pkg != "gen" {
		b.WriteString("\t\"github.com/milon-labs/milon-go-sdk/gen\"\n")
	}
	b.WriteString("\t\"github.com/milon-labs/milon-go-sdk/provider\"\n")
	b.WriteString(")\n\n")

	// 1. IDL data constants, mirroring the JS SDK's DEFAULT_IDLS (as const).
	writeDefaultIDLs(&b, apps)

	// 2. Typed definitions for every custom IDL type (struct/enum).
	for _, app := range apps {
		generateCustomTypes(&b, app, &imp)
	}

	// 3. Decoded-value converters (map[string]any -> generated structs).
	for _, app := range apps {
		generateFromFuncs(&b, app, &imp)
	}

	// 3b. Wire-value converters (generated structs -> provider serialization
	// values), backing the typed instruction arguments.
	for _, app := range apps {
		generateToFuncs(&b, app)
	}

	// 4. Typed instruction builders.
	for _, app := range apps {
		generateApp(&b, app, &imp)
	}

	// 5. Value conversion helpers used by the generated code above.
	writeHelpers(&b)

	b.WriteString("func init() {\n")
	for _, app := range apps {
		reg := "RegisterApp"
		if pkg != "gen" {
			reg = "gen.RegisterApp"
		}
		fmt.Fprintf(&b, "\t%s(%q, func(pd *provider.Provider) error { %s.bind(pd); return nil })\n", reg, app.name, pascal(app.name))
	}
	b.WriteString("}\n")

	return b.String(), nil
}

// writeDefaultIDLs emits DefaultIDLs, an inline constant array of every IDL,
// equivalent to the JS SDK's `export const DEFAULT_IDLS = [...] as const`.
func writeDefaultIDLs(b *strings.Builder, apps []appInfo) {
	b.WriteString("// DefaultIDLs contains every IDL definition as inline constants,\n")
	b.WriteString("// mirroring the JS SDK's DEFAULT_IDLS (as const).\n")
	b.WriteString("var DefaultIDLs = []provider.IDL{\n")
	for _, app := range apps {
		writeValue(b, reflect.ValueOf(app.idl), "\t")
		b.WriteString(",\n")
	}
	b.WriteString("}\n\n")
}

// writeValue writes a Go literal of the reflect value.
func writeValue(b *strings.Builder, v reflect.Value, indent string) {
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			b.WriteString("nil")
			return
		}
		b.WriteString("&")
		v = v.Elem()
	}

	switch v.Kind() {
	case reflect.String:
		fmt.Fprintf(b, "%q", v.String())
	case reflect.Bool:
		fmt.Fprintf(b, "%t", v.Bool())
	case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uint:
		fmt.Fprintf(b, "%d", v.Uint())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fmt.Fprintf(b, "%d", v.Int())
	case reflect.Float64:
		f := v.Float()
		if f == float64(int64(f)) {
			fmt.Fprintf(b, "%d", int64(f))
		} else {
			fmt.Fprintf(b, "%v", f)
		}
	case reflect.Slice:
		if v.Len() == 0 {
			b.WriteString("nil")
			return
		}
		fmt.Fprintf(b, "[]%s{\n", v.Type().Elem().String())
		for i := 0; i < v.Len(); i++ {
			b.WriteString(indent + "\t")
			writeValue(b, v.Index(i), indent+"\t")
			b.WriteString(",\n")
		}
		b.WriteString(indent + "}")
	case reflect.Map:
		if v.Len() == 0 {
			b.WriteString("nil")
			return
		}
		fmt.Fprintf(b, "%s{\n", v.Type().String())
		keys := v.MapKeys()
		sort.Slice(keys, func(i, j int) bool {
			return fmt.Sprintf("%v", keys[i].Interface()) < fmt.Sprintf("%v", keys[j].Interface())
		})
		for _, k := range keys {
			b.WriteString(indent + "\t")
			writeValue(b, k, indent+"\t")
			b.WriteString(": ")
			writeValue(b, v.MapIndex(k), indent+"\t")
			b.WriteString(",\n")
		}
		b.WriteString(indent + "}")
	case reflect.Struct:
		fmt.Fprintf(b, "%s{\n", v.Type().String())
		for i := 0; i < v.NumField(); i++ {
			fv := v.Field(i)
			if fv.IsZero() {
				continue
			}
			b.WriteString(indent + "\t" + v.Type().Field(i).Name + ": ")
			writeValue(b, fv, indent+"\t")
			b.WriteString(",\n")
		}
		b.WriteString(indent + "}")
	default:
		fmt.Fprintf(b, "%#v", v.Interface())
	}
}

// buildTypeMap indexes the custom IDL types of an app by name.
func buildTypeMap(app appInfo) map[string]provider.IDLType {
	types := make(map[string]provider.IDLType)
	for _, t := range app.idl.Types {
		// Only struct/enum types are emitted as generated types; builtin
		// entries (u64, Address, String, ...) must resolve to Go built-ins.
		if t.Kind == "struct" || t.Kind == "enum" {
			types[t.Name] = t
		}
	}
	return types
}

// goTypeName returns the generated Go type name of a custom IDL type,
// prefixed with the app name to avoid collisions across apps.
func goTypeName(appName, idlName string) string {
	return pascal(appName) + idlName
}

// goReturnType maps an IDL type to the Go type used for view return values,
// generated struct fields and instruction arguments. Custom IDL types
// resolve to the generated structs instead of any.
func goReturnType(idlType string, imp *importSet, appName string, types map[string]provider.IDLType) string {
	t := strings.TrimSpace(idlType)
	if inner, ok := wrappedInner(t, "vec"); ok {
		return "[]" + goReturnType(inner, imp, appName, types)
	}
	if inner, ok := wrappedInner(t, "option"); ok {
		return "*" + goReturnType(inner, imp, appName, types)
	}
	if strings.HasPrefix(t, "map<") && strings.HasSuffix(t, ">") {
		parts := splitTopLevel(t[4 : len(t)-1])
		if len(parts) == 2 {
			return "map[" + goReturnType(parts[0], imp, appName, types) + "]" + goReturnType(parts[1], imp, appName, types)
		}
	}
	if strings.HasPrefix(t, "tuple<") && strings.HasSuffix(t, ">") {
		return "[]any"
	}
	if _, ok := types[t]; ok {
		return goTypeName(appName, t)
	}
	return goType(t, imp)
}

// generateCustomTypes emits a Go type definition for every custom struct and
// enum declared in the IDL, e.g. TokenMetadata or TokenComplianceMode, plus
// the ToValue method that converts the typed value into the wire form.
func generateCustomTypes(b *strings.Builder, app appInfo, imp *importSet) {
	typeByName := buildTypeMap(app)
	for _, t := range app.idl.Types {
		if t.Kind != "struct" && t.Kind != "enum" {
			continue
		}
		goName := goTypeName(app.name, t.Name)
		switch t.Kind {
		case "struct":
			fmt.Fprintf(b, "// %s matches the IDL struct %s.\n", goName, t.Name)
			fmt.Fprintf(b, "type %s struct {\n", goName)
			for _, f := range t.Fields {
				fmt.Fprintf(b, "\t%s %s\n", pascal(f.Name), goReturnType(f.Type, imp, app.name, typeByName))
			}
			fmt.Fprintf(b, "}\n\n")
			writeToValueStruct(b, goName, t, app.name, typeByName)
		case "enum":
			fmt.Fprintf(b, "// %s matches the IDL enum %s.\n", goName, t.Name)
			fmt.Fprintf(b, "type %s struct {\n", goName)
			fmt.Fprintf(b, "\tVariant string // Active variant name\n")
			fmt.Fprintf(b, "\tIndex   uint64 // Active variant index\n")
			fmt.Fprintf(b, "\tFields  []any  // Fields of the active variant, in declaration order; nil for unit variants\n")
			fmt.Fprintf(b, "}\n\n")
			writeToValueEnum(b, goName, t, app.name, typeByName)
		}
	}
}

// generateFromFuncs emits a converter for every custom IDL type, turning the
// map[string]any value produced by the provider deserializer into the
// generated struct.
func generateFromFuncs(b *strings.Builder, app appInfo, imp *importSet) {
	typeByName := buildTypeMap(app)
	for _, t := range app.idl.Types {
		if t.Kind != "struct" && t.Kind != "enum" {
			continue
		}
		goName := goTypeName(app.name, t.Name)
		switch t.Kind {
		case "struct":
			writeFromStruct(b, goName, t, app.name, typeByName, imp)
		case "enum":
			writeFromEnum(b, goName, t)
		}
	}
}

func writeFromStruct(b *strings.Builder, goName string, t provider.IDLType, appName string, types map[string]provider.IDLType, imp *importSet) {
	fmt.Fprintf(b, "// from%s converts a decoded IDL value into %s.\n", goName, goName)
	fmt.Fprintf(b, "func from%s(v any) (out %s, err error) {\n", goName, goName)
	fmt.Fprintf(b, "\tm, err := toRecord(v)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn out, err\n\t}\n")
	var counter int
	for _, f := range t.Fields {
		fmt.Fprintf(b, "\t// %s: %s\n", f.Name, f.Type)
		fmt.Fprintf(b, "\t{\n")
		writeConvStmt(b, "out."+pascal(f.Name), fmt.Sprintf("m[%q]", f.Name), f.Type, "\t\t", appName, types, &counter)
		fmt.Fprintf(b, "\t}\n")
	}
	fmt.Fprintf(b, "\treturn out, nil\n}\n\n")
}

func writeFromEnum(b *strings.Builder, goName string, t provider.IDLType) {
	fmt.Fprintf(b, "// from%s converts a decoded IDL value into %s.\n", goName, goName)
	fmt.Fprintf(b, "func from%s(v any) (out %s, err error) {\n", goName, goName)
	fmt.Fprintf(b, "\tm, err := toRecord(v)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn out, err\n\t}\n")
	fmt.Fprintf(b, "\ts, ok := m[\"variant\"].(string)\n")
	fmt.Fprintf(b, "\tif !ok {\n\t\treturn out, fmt.Errorf(\"enum %s: missing variant\")\n\t}\n", t.Name)
	fmt.Fprintf(b, "\tout.Variant = s\n")
	fmt.Fprintf(b, "\tn, err := toUint(m[\"index\"])\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn out, err\n\t}\n")
	fmt.Fprintf(b, "\tout.Index = n\n")

	hasFields := false
	for _, v := range t.Variants {
		if len(v.Fields) > 0 {
			hasFields = true
			break
		}
	}
	if hasFields {
		fmt.Fprintf(b, "\tswitch out.Variant {\n")
		for _, v := range t.Variants {
			if len(v.Fields) == 0 {
				continue
			}
			fmt.Fprintf(b, "\tcase %q:\n", v.Name)
			if v.Kind == "tuple" {
				fmt.Fprintf(b, "\t\tif f, ok := m[\"fields\"].([]any); ok {\n\t\t\tout.Fields = f\n\t\t}\n")
			} else {
				fmt.Fprintf(b, "\t\tout.Fields = []any{\n")
				for _, f := range v.Fields {
					fmt.Fprintf(b, "\t\t\tm[%q],\n", f.Name)
				}
				fmt.Fprintf(b, "\t\t}\n")
			}
		}
		fmt.Fprintf(b, "\t}\n")
	}
	fmt.Fprintf(b, "\treturn out, nil\n}\n\n")
}

// writeToValueStruct emits ToValue, converting the generated struct into the
// map[string]any form the provider serializer expects (keys are IDL field
// names, values are typed and converted recursively).
func writeToValueStruct(b *strings.Builder, goName string, t provider.IDLType, appName string, types map[string]provider.IDLType) {
	fmt.Fprintf(b, "// ToValue converts %s into the provider wire value (map[string]any).\n", goName)
	fmt.Fprintf(b, "func (v %s) ToValue() (map[string]any, error) {\n", goName)
	fmt.Fprintf(b, "\tout := make(map[string]any, %d)\n", len(t.Fields))
	var counter int
	for _, f := range t.Fields {
		fmt.Fprintf(b, "\t// %s: %s\n", f.Name, f.Type)
		writeToStmt(b, fmt.Sprintf("out[%q]", f.Name), "v."+pascal(f.Name), f.Type, "\t", appName, types, &counter)
	}
	fmt.Fprintf(b, "\treturn out, nil\n}\n\n")
}

// writeToValueEnum emits ToValue, converting the generated enum into the
// map[string]any form the provider serializer expects: {"variant": name,
// "fields": ...} where fields is absent for unit variants, a record for
// struct variants and an array for tuple variants.
func writeToValueEnum(b *strings.Builder, goName string, t provider.IDLType, appName string, types map[string]provider.IDLType) {
	fmt.Fprintf(b, "// ToValue converts %s into the provider wire value (map[string]any).\n", goName)
	fmt.Fprintf(b, "func (v %s) ToValue() (map[string]any, error) {\n", goName)
	fmt.Fprintf(b, "\tif v.Variant == \"\" {\n\t\treturn nil, fmt.Errorf(\"enum %s: empty variant\")\n\t}\n", t.Name)
	fmt.Fprintf(b, "\tswitch v.Variant {\n")
	for _, variant := range t.Variants {
		fmt.Fprintf(b, "\tcase %q:\n", variant.Name)
		switch variant.Kind {
		case "unit":
			fmt.Fprintf(b, "\t\treturn map[string]any{\"variant\": %q}, nil\n", variant.Name)
		case "tuple":
			fmt.Fprintf(b, "\t\tif len(v.Fields) != %d {\n\t\t\treturn nil, fmt.Errorf(\"enum %s: variant %s expects %%d fields\", len(v.Fields))\n\t\t}\n", len(variant.Fields), t.Name, variant.Name)
			var counter int
			fields := make([]string, 0, len(variant.Fields))
			for i, f := range variant.Fields {
				tmp := fmt.Sprintf("v%d", counter)
				counter++
				fmt.Fprintf(b, "\t\tvar %s any\n", tmp)
				writeToStmt(b, tmp, fmt.Sprintf("v.Fields[%d]", i), f.Type, "\t\t", appName, types, &counter)
				fields = append(fields, tmp)
			}
			fmt.Fprintf(b, "\t\treturn map[string]any{\"variant\": %q, \"fields\": []any{%s}}, nil\n", variant.Name, strings.Join(fields, ", "))
		case "struct":
			fmt.Fprintf(b, "\t\tif len(v.Fields) != %d {\n\t\t\treturn nil, fmt.Errorf(\"enum %s: variant %s expects %%d fields\", len(v.Fields))\n\t\t}\n", len(variant.Fields), t.Name, variant.Name)
			fmt.Fprintf(b, "\t\trecord := make(map[string]any, %d)\n", len(variant.Fields))
			var counter int
			for i, f := range variant.Fields {
				fmt.Fprintf(b, "\t\t// %s: %s\n", f.Name, f.Type)
				writeToStmt(b, fmt.Sprintf("record[%q]", f.Name), fmt.Sprintf("v.Fields[%d]", i), f.Type, "\t\t", appName, types, &counter)
			}
			fmt.Fprintf(b, "\t\treturn map[string]any{\"variant\": %q, \"fields\": record}, nil\n", variant.Name)
		}
	}
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn nil, fmt.Errorf(\"unknown variant %%q\", v.Variant)\n")
	fmt.Fprintf(b, "}\n\n")
}

// generateToFuncs emits a converter for every custom IDL type, turning any
// input (value or pointer) into the wire value used by provider serialization.
func generateToFuncs(b *strings.Builder, app appInfo) {
	for _, t := range app.idl.Types {
		if t.Kind != "struct" && t.Kind != "enum" {
			continue
		}
		goName := goTypeName(app.name, t.Name)
		fmt.Fprintf(b, "// to%sValue converts any into %s for provider serialization.\n", goName, goName)
		fmt.Fprintf(b, "func to%sValue(v any) (map[string]any, error) {\n", goName)
		fmt.Fprintf(b, "\tswitch x := v.(type) {\n")
		fmt.Fprintf(b, "\tcase %s:\n\t\treturn x.ToValue()\n", goName)
		fmt.Fprintf(b, "\tcase *%s:\n", goName)
		fmt.Fprintf(b, "\t\tif x == nil {\n\t\t\treturn nil, fmt.Errorf(\"nil %s\")\n\t\t}\n", goName)
		fmt.Fprintf(b, "\t\treturn x.ToValue()\n")
		fmt.Fprintf(b, "\tdefault:\n\t\treturn nil, fmt.Errorf(\"expected %s, got %%T\", v)\n", goName)
		fmt.Fprintf(b, "\t}\n}\n\n")
	}
}

// writeConvStmt writes statements converting an untyped value (vExpr) of the
// given IDL type into a typed value assigned to outVar. The generated code
// relies on an enclosing function with named results (out T, err error).
func writeConvStmt(b *strings.Builder, outVar, vExpr, idlType, indent, appName string, types map[string]provider.IDLType, counter *int) {
	t := strings.TrimSpace(idlType)
	next := func() string {
		v := fmt.Sprintf("v%d", *counter)
		*counter++
		return v
	}

	if inner, ok := wrappedInner(t, "vec"); ok {
		tmp := next()
		fmt.Fprintf(b, "%s%s, err := toSlice(%s)\n", indent, tmp, vExpr)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, err\n%s}\n", indent, indent, indent)
		fmt.Fprintf(b, "%s%s = make([]%s, len(%s))\n", indent, outVar, goReturnType(inner, &importSet{}, appName, types), tmp)
		idx, elem := next(), next()
		fmt.Fprintf(b, "%sfor %s, %s := range %s {\n", indent, idx, elem, tmp)
		writeConvStmt(b, outVar+"["+idx+"]", elem, inner, indent+"\t", appName, types, counter)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}

	if inner, ok := wrappedInner(t, "option"); ok {
		fmt.Fprintf(b, "%sif %s == nil {\n", indent, vExpr)
		fmt.Fprintf(b, "%s\t%s = nil\n", indent, outVar)
		fmt.Fprintf(b, "%s} else {\n", indent)
		tmp := next()
		fmt.Fprintf(b, "%s\tvar %s %s\n", indent, tmp, goReturnType(inner, &importSet{}, appName, types))
		writeConvStmt(b, tmp, vExpr, inner, indent+"\t", appName, types, counter)
		fmt.Fprintf(b, "%s\t%s = &%s\n", indent, outVar, tmp)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}

	if strings.HasPrefix(t, "map<") && strings.HasSuffix(t, ">") {
		parts := splitTopLevel(t[4 : len(t)-1])
		if len(parts) == 2 {
			tmp := next()
			fmt.Fprintf(b, "%s%s, err := toMap(%s)\n", indent, tmp, vExpr)
			fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, err\n%s}\n", indent, indent, indent)
			fmt.Fprintf(b, "%s%s = make(map[%s]%s, len(%s))\n", indent, outVar,
				goReturnType(parts[0], &importSet{}, appName, types), goReturnType(parts[1], &importSet{}, appName, types), tmp)
			kk, ee := next(), next()
			fmt.Fprintf(b, "%sfor %s, %s := range %s {\n", indent, kk, ee, tmp)
			ck, cv := next(), next()
			fmt.Fprintf(b, "%s\tvar %s %s\n", indent, ck, goReturnType(parts[0], &importSet{}, appName, types))
			fmt.Fprintf(b, "%s\tvar %s %s\n", indent, cv, goReturnType(parts[1], &importSet{}, appName, types))
			writeConvStmt(b, ck, kk, parts[0], indent+"\t", appName, types, counter)
			writeConvStmt(b, cv, ee, parts[1], indent+"\t", appName, types, counter)
			fmt.Fprintf(b, "%s\t%s[%s] = %s\n", indent, outVar, ck, cv)
			fmt.Fprintf(b, "%s}\n", indent)
			return
		}
	}

	if strings.HasPrefix(t, "tuple<") && strings.HasSuffix(t, ">") {
		tmp := next()
		fmt.Fprintf(b, "%s%s, err := toSlice(%s)\n", indent, tmp, vExpr)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, err\n%s}\n", indent, indent, indent)
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	if _, ok := types[t]; ok {
		tmp := next()
		fmt.Fprintf(b, "%s%s, err := from%s(%s)\n", indent, tmp, goTypeName(appName, t), vExpr)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, err\n%s}\n", indent, indent, indent)
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	helper := map[string]string{
		"Address": "toAddress", "Signer": "toAddress", "AnySigner": "toAddress",
		"PublicKey": "toPublicKey",
		"String":    "toString", "string": "toString",
		"bool": "toBool", "boolean": "toBool",
		"u8": "toUint8", "u16": "toUint16", "u32": "toUint32",
		"u64": "toUint64", "Bitmap64": "toUint64", "Amount": "toUint64", "Epoch": "toUint64",
		"u128": "toBigInt",
		"i8":   "toInt8", "i16": "toInt16", "i32": "toInt32", "i64": "toInt64",
		"bytes": "toBytes",
		"B96":   "toFixed12", "B144": "toFixed18", "B160": "toFixed20", "B256": "toFixed32",
	}[t]
	if helper != "" {
		tmp := next()
		fmt.Fprintf(b, "%s%s, err := %s(%s)\n", indent, tmp, helper, vExpr)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, err\n%s}\n", indent, indent, indent)
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	// Unknown IDL type: keep the decoded value as-is.
	fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, vExpr)
}

// writeToStmt writes statements converting a typed value (vExpr) of the given
// IDL type into the untyped wire value expected by the provider serializer,
// assigning it to outVar. outVar must already be assignable (a map element or
// a declared variable). Generated code relies on an enclosing function whose
// error result can be returned with "return nil, err".
func writeToStmt(b *strings.Builder, outVar, vExpr, idlType, indent, appName string, types map[string]provider.IDLType, counter *int) {
	t := strings.TrimSpace(idlType)
	next := func() string {
		v := fmt.Sprintf("v%d", *counter)
		*counter++
		return v
	}

	if inner, ok := wrappedInner(t, "vec"); ok {
		tmp := next()
		fmt.Fprintf(b, "%s%s := make([]any, len(%s))\n", indent, tmp, vExpr)
		idx, elem := next(), next()
		fmt.Fprintf(b, "%sfor %s, %s := range %s {\n", indent, idx, elem, vExpr)
		writeToStmt(b, tmp+"["+idx+"]", elem, inner, indent+"\t", appName, types, counter)
		fmt.Fprintf(b, "%s}\n", indent)
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	if inner, ok := wrappedInner(t, "option"); ok {
		fmt.Fprintf(b, "%sif %s == nil {\n", indent, vExpr)
		fmt.Fprintf(b, "%s\t%s = nil\n", indent, outVar)
		fmt.Fprintf(b, "%s} else {\n", indent)
		writeToStmt(b, outVar, "*"+vExpr, inner, indent+"\t", appName, types, counter)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}

	if strings.HasPrefix(t, "map<") && strings.HasSuffix(t, ">") {
		parts := splitTopLevel(t[4 : len(t)-1])
		if len(parts) == 2 {
			tmp := next()
			fmt.Fprintf(b, "%s%s := make(map[any]any, len(%s))\n", indent, tmp, vExpr)
			kk, ee := next(), next()
			fmt.Fprintf(b, "%sfor %s, %s := range %s {\n", indent, kk, ee, vExpr)
			ck, cv := next(), next()
			fmt.Fprintf(b, "%s\tvar %s any\n", indent, ck)
			fmt.Fprintf(b, "%s\tvar %s any\n", indent, cv)
			writeToStmt(b, ck, kk, parts[0], indent+"\t", appName, types, counter)
			writeToStmt(b, cv, ee, parts[1], indent+"\t", appName, types, counter)
			fmt.Fprintf(b, "%s\t%s[%s] = %s\n", indent, tmp, ck, cv)
			fmt.Fprintf(b, "%s}\n", indent)
			fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
			return
		}
	}

	if strings.HasPrefix(t, "tuple<") && strings.HasSuffix(t, ">") {
		parts := splitTopLevel(t[4 : len(t)-1])
		tmp := next()
		fmt.Fprintf(b, "%s%s := make([]any, %d)\n", indent, tmp, len(parts))
		for i, pt := range parts {
			writeToStmt(b, fmt.Sprintf("%s[%d]", tmp, i), fmt.Sprintf("%s[%d]", vExpr, i), pt, indent, appName, types, counter)
		}
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	if _, ok := types[t]; ok {
		tmp := next()
		fmt.Fprintf(b, "%s%s, err := to%sValue(%s)\n", indent, tmp, goTypeName(appName, t), vExpr)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn nil, err\n%s}\n", indent, indent, indent)
		fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, tmp)
		return
	}

	// Builtin or unknown: keep the typed value as-is; the provider
	// serializer accepts concrete Go values for every builtin type.
	fmt.Fprintf(b, "%s%s = %s\n", indent, outVar, vExpr)
}

func generateApp(b *strings.Builder, app appInfo, imp *importSet) {
	appVar := pascal(app.name)
	appType := appVar + "App"
	typeByName := buildTypeMap(app)

	fmt.Fprintf(b, "// %s exposes type-safe instruction builders for IDL app %q.\n", appType, app.name)
	fmt.Fprintf(b, "type %s struct {\n", appType)
	fmt.Fprintf(b, "\tPd *provider.Provider\n")
	for _, ix := range app.idl.Instructions {
		ixType := pascal(app.name) + ix.Name + "Ix"
		fmt.Fprintf(b, "\t%s *%s\n", ix.Name, ixType)
	}
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "var %s = &%s{\n", appVar, appType)
	for _, ix := range app.idl.Instructions {
		ixType := pascal(app.name) + ix.Name + "Ix"
		fmt.Fprintf(b, "\t%s: &%s{},\n", ix.Name, ixType)
	}
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "func (a *%s) bind(pd *provider.Provider) {\n", appType)
	fmt.Fprintf(b, "\ta.Pd = pd\n")
	for _, ix := range app.idl.Instructions {
		fmt.Fprintf(b, "\ta.%s.pd = pd\n", ix.Name)
	}
	fmt.Fprintf(b, "}\n\n")

	for _, ix := range app.idl.Instructions {
		generateIx(b, app, ix, imp, typeByName)
	}
}

func generateIx(b *strings.Builder, app appInfo, ix provider.Instruction, imp *importSet, typeByName map[string]provider.IDLType) {
	ixType := pascal(app.name) + ix.Name + "Ix"
	argsType := pascal(app.name) + ix.Name + "Args"

	fmt.Fprintf(b, "type %s struct {\n\tpd *provider.Provider\n}\n\n", ixType)

	fmt.Fprintf(b, "type %s struct {\n", argsType)
	for _, arg := range ix.Args {
		fmt.Fprintf(b, "\t%s %s\n", goParamName(arg.Name), goReturnType(arg.Type, imp, app.name, typeByName))
	}
	fmt.Fprintf(b, "\tpd *provider.Provider\n")
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "// Args builds the IDL arguments of %s.\n", ix.Name)
	fmt.Fprintf(b, "func (ix *%s) Args(", ixType)
	params := make([]string, 0, len(ix.Args))
	for _, arg := range ix.Args {
		params = append(params, fmt.Sprintf("%s %s", goParamName(arg.Name), goReturnType(arg.Type, imp, app.name, typeByName)))
	}
	b.WriteString(strings.Join(params, ", "))
	fmt.Fprintf(b, ") *%s {\n", argsType)
	fmt.Fprintf(b, "\treturn &%s{\n", argsType)
	for _, arg := range ix.Args {
		fmt.Fprintf(b, "\t\t%s: %s,\n", goParamName(arg.Name), goParamName(arg.Name))
	}
	fmt.Fprintf(b, "\t\tpd: ix.pd,\n")
	fmt.Fprintf(b, "\t}\n}\n\n")

	fmt.Fprintf(b, "// Encode serializes the arguments into a PackedInstruction.\n")
	fmt.Fprintf(b, "func (a *%s) Encode() (api.PackedInstruction, error) {\n", argsType)
	fmt.Fprintf(b, "\tif a.pd == nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"IDL app %s is not bound: call milon.NewClient first\")\n", app.name)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\targs := provider.Args{}\n")
	var counter int
	for _, arg := range ix.Args {
		fmt.Fprintf(b, "\t// %s: %s\n", arg.Name, arg.Type)
		writeToStmt(b, fmt.Sprintf("args[%q]", arg.Name), "a."+goParamName(arg.Name), arg.Type, "\t", app.name, typeByName, &counter)
	}
	fmt.Fprintf(b, "\twire, err := a.pd.Encode(%q, args)\n", ix.Name)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\treturn api.PackedInstruction(wire), nil\n")
	fmt.Fprintf(b, "}\n\n")

	if ix.Kind == "view" && ix.Returns.Type != "" {
		retType := goReturnType(ix.Returns.Type, imp, app.name, typeByName)
		fmt.Fprintf(b, "// DecodeView decodes the raw view response body of %s into %s.\n", ix.Name, retType)
		fmt.Fprintf(b, "func (ix *%s) DecodeView(body []byte) (out %s, err error) {\n", ixType, retType)
		fmt.Fprintf(b, "\tif ix.pd == nil {\n")
		fmt.Fprintf(b, "\t\treturn out, fmt.Errorf(\"IDL app %s is not bound: call milon.NewClient first\")\n", app.name)
		fmt.Fprintf(b, "\t}\n")
		fmt.Fprintf(b, "\tv, err := ix.pd.DecodeViewData(%q, body)\n", ix.Name)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn out, err\n\t}\n")
		fmt.Fprintf(b, "\tif failure, ok := v.(*api.TxFailurePayload); ok {\n")
		fmt.Fprintf(b, "\t\treturn out, fmt.Errorf(\"view %s failed: code=%%d msg=%%q\", failure.Code, failure.Message)\n", ix.Name)
		fmt.Fprintf(b, "\t}\n")
		var convCounter int
		writeConvStmt(b, "out", "v", ix.Returns.Type, "\t", app.name, typeByName, &convCounter)
		fmt.Fprintf(b, "\treturn out, nil\n")
		fmt.Fprintf(b, "}\n\n")
	}
}

// writeHelpers emits the conversion helpers shared by all generated code.
func writeHelpers(b *strings.Builder) {
	b.WriteString(`// ---- value conversion helpers (generated) ----

func toRecord(v any) (map[string]any, error) {
	m, ok := v.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("expected record, got %T", v)
	}
	return m, nil
}

func toMap(v any) (map[any]any, error) {
	m, ok := v.(map[any]any)
	if !ok {
		return nil, fmt.Errorf("expected map, got %T", v)
	}
	return m, nil
}

func toSlice(v any) ([]any, error) {
	s, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("expected slice, got %T", v)
	}
	return s, nil
}

func toUint(v any) (uint64, error) {
	switch n := v.(type) {
	case uint64:
		return n, nil
	case uint32:
		return uint64(n), nil
	case uint16:
		return uint64(n), nil
	case uint8:
		return uint64(n), nil
	case uint:
		return uint64(n), nil
	case int64:
		return uint64(n), nil
	case int32:
		return uint64(n), nil
	case int16:
		return uint64(n), nil
	case int8:
		return uint64(n), nil
	case int:
		return uint64(n), nil
	case float64:
		return uint64(n), nil
	}
	return 0, fmt.Errorf("expected unsigned integer, got %T", v)
}

func toInt(v any) (int64, error) {
	switch n := v.(type) {
	case int64:
		return n, nil
	case int32:
		return int64(n), nil
	case int16:
		return int64(n), nil
	case int8:
		return int64(n), nil
	case int:
		return int64(n), nil
	case uint64:
		return int64(n), nil
	case uint32:
		return int64(n), nil
	case uint16:
		return int64(n), nil
	case uint8:
		return int64(n), nil
	case uint:
		return int64(n), nil
	case float64:
		return int64(n), nil
	}
	return 0, fmt.Errorf("expected signed integer, got %T", v)
}

func toUint8(v any) (uint8, error) {
	n, err := toUint(v)
	return uint8(n), err
}

func toUint16(v any) (uint16, error) {
	n, err := toUint(v)
	return uint16(n), err
}

func toUint32(v any) (uint32, error) {
	n, err := toUint(v)
	return uint32(n), err
}

func toUint64(v any) (uint64, error) {
	return toUint(v)
}

func toInt8(v any) (int8, error) {
	n, err := toInt(v)
	return int8(n), err
}

func toInt16(v any) (int16, error) {
	n, err := toInt(v)
	return int16(n), err
}

func toInt32(v any) (int32, error) {
	n, err := toInt(v)
	return int32(n), err
}

func toInt64(v any) (int64, error) {
	return toInt(v)
}

func toString(v any) (string, error) {
	if s, ok := v.(string); ok {
		return s, nil
	}
	return "", fmt.Errorf("expected string, got %T", v)
}

func toBool(v any) (bool, error) {
	if x, ok := v.(bool); ok {
		return x, nil
	}
	return false, fmt.Errorf("expected bool, got %T", v)
}

func toBytes(v any) ([]byte, error) {
	if x, ok := v.([]byte); ok {
		return x, nil
	}
	return nil, fmt.Errorf("expected []byte, got %T", v)
}

func toAddress(v any) (*crypto.Address, error) {
	if x, ok := v.(*crypto.Address); ok {
		return x, nil
	}
	return nil, fmt.Errorf("expected *crypto.Address, got %T", v)
}

func toPublicKey(v any) (*crypto.PublicKey, error) {
	if x, ok := v.(*crypto.PublicKey); ok {
		return x, nil
	}
	return nil, fmt.Errorf("expected *crypto.PublicKey, got %T", v)
}

func toBigInt(v any) (*big.Int, error) {
	switch n := v.(type) {
	case *big.Int:
		return n, nil
	case uint64:
		return new(big.Int).SetUint64(n), nil
	case uint32:
		return new(big.Int).SetUint64(uint64(n)), nil
	case uint16:
		return new(big.Int).SetUint64(uint64(n)), nil
	case uint8:
		return new(big.Int).SetUint64(uint64(n)), nil
	case string:
		x, ok := new(big.Int).SetString(n, 10)
		if !ok {
			return nil, fmt.Errorf("invalid big.Int string %q", n)
		}
		return x, nil
	}
	return nil, fmt.Errorf("expected *big.Int, got %T", v)
}

func toFixed12(v any) ([12]byte, error) {
	switch n := v.(type) {
	case [12]byte:
		return n, nil
	case []byte:
		var out [12]byte
		copy(out[:], n)
		return out, nil
	}
	return [12]byte{}, fmt.Errorf("expected [12]byte, got %T", v)
}

func toFixed18(v any) ([18]byte, error) {
	switch n := v.(type) {
	case [18]byte:
		return n, nil
	case []byte:
		var out [18]byte
		copy(out[:], n)
		return out, nil
	}
	return [18]byte{}, fmt.Errorf("expected [18]byte, got %T", v)
}

func toFixed20(v any) ([20]byte, error) {
	switch n := v.(type) {
	case [20]byte:
		return n, nil
	case []byte:
		var out [20]byte
		copy(out[:], n)
		return out, nil
	}
	return [20]byte{}, fmt.Errorf("expected [20]byte, got %T", v)
}

func toFixed32(v any) ([32]byte, error) {
	switch n := v.(type) {
	case [32]byte:
		return n, nil
	case []byte:
		var out [32]byte
		copy(out[:], n)
		return out, nil
	}
	return [32]byte{}, fmt.Errorf("expected [32]byte, got %T", v)
}
`)
}

// goType maps an IDL type to a Go type for the builtin cases, used as the
// fallback of goReturnType.
func goType(idlType string, imp *importSet) string {
	t := strings.TrimSpace(idlType)
	if inner, ok := wrappedInner(t, "vec"); ok {
		return "[]" + goType(inner, imp)
	}
	if inner, ok := wrappedInner(t, "option"); ok {
		return "*" + goType(inner, imp)
	}
	if strings.HasPrefix(t, "map<") && strings.HasSuffix(t, ">") {
		parts := splitTopLevel(t[4 : len(t)-1])
		if len(parts) == 2 {
			return "map[" + goType(parts[0], imp) + "]" + goType(parts[1], imp)
		}
	}
	if strings.HasPrefix(t, "tuple<") && strings.HasSuffix(t, ">") {
		return "[]any"
	}
	switch t {
	case "Address", "Signer", "AnySigner":
		imp.crypto = true
		return "*crypto.Address"
	case "PublicKey":
		imp.crypto = true
		return "*crypto.PublicKey"
	case "String", "string":
		return "string"
	case "bool", "boolean":
		return "bool"
	case "u8":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32":
		return "uint32"
	case "u64", "Bitmap64", "Amount", "Epoch":
		return "uint64"
	case "u128":
		imp.big = true
		return "*big.Int"
	case "i8":
		return "int8"
	case "i16":
		return "int16"
	case "i32":
		return "int32"
	case "i64":
		return "int64"
	case "bytes":
		return "[]byte"
	case "B96":
		return "[12]byte"
	case "B144":
		return "[18]byte"
	case "B160":
		return "[20]byte"
	case "B256":
		return "[32]byte"
	default:
		// Unknown IDL type: fall back to any.
		return "any"
	}
}

func wrappedInner(t, wrapper string) (string, bool) {
	prefix := wrapper + "<"
	if strings.HasPrefix(t, prefix) && strings.HasSuffix(t, ">") {
		return t[len(prefix) : len(t)-1], true
	}
	return "", false
}

// splitTopLevel splits s by top-level commas (ignores nested <>).
func splitTopLevel(s string) []string {
	var parts []string
	depth := 0
	start := 0
	for i, r := range s {
		switch r {
		case '<':
			depth++
		case '>':
			depth--
		case ',':
			if depth == 0 {
				parts = append(parts, strings.TrimSpace(s[start:i]))
				start = i + 1
			}
		}
	}
	parts = append(parts, strings.TrimSpace(s[start:]))
	return parts
}

var goKeywords = map[string]bool{
	"break": true, "default": true, "func": true, "interface": true, "select": true,
	"case": true, "defer": true, "go": true, "map": true, "struct": true,
	"chan": true, "else": true, "goto": true, "package": true, "switch": true,
	"const": true, "fallthrough": true, "if": true, "range": true, "type": true,
	"continue": true, "for": true, "import": true, "return": true, "var": true,
}

func goParamName(name string) string {
	if goKeywords[name] {
		return name + "_"
	}
	return name
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}
